### ISSUE TITLE
How to modify elements used in DriverPower

### ISSUE THREAD

**Issue by yasunorikogure** [smshuai/DriverPower#13]
Hello,
I'm wondering how I can modify "elements" used in DriverPower. I suppose the feature hdf5 files are fixed according to the Gencode elements in the tutorial data. How can I generate other user-defined elements, such as conserved regions or super-enhancers? I couldn't find the information about where the tracks of the feature table came from.
Thanks in advance.

**Comment by smshuai** [comment]
Hi Yasunori,

Thanks for using DriverPower! DriverPower supports all types of test elements. However, you need to prepare a feature table for your own test elements. I have a local database of raw data that I use to calculate features for each element but I have trouble hosting it.

If you want to use the same features I used, I can share a spreadsheet with you so you can set up a local database for yourself. Alternatively, you can just pick features that suit your tumour type of interest and make sure that training and test data use the same set of features.

Best,
Shimin

**Comment by yasunorikogure** [comment]
Hi Shimin,

Thank you for your offer. I'd appreciate if you could share the same spreadsheet as you have used, and also the script to generate an hdf5 file from the database.

Best,
Yasunori

**Comment by smshuai** [comment]
Hi Yasunori,

The spreadsheet is [here](https://raw.githubusercontent.com/smshuai/DriverPower/master/data/DriverPower_Supplementary_Data_2.csv). The URL column is the address of raw features. Columns after that are feature importance I got based on my data. If you can find your tumour type there, then perhaps you only need to download a fraction of features (e.g., feature importance > 0.5 or another cut-off).

Notes:
1. URLs of three conservation features (pphastCons46way, pphyloP46way and vphastCons46way) are linked to directories but not files because the data are for each chromosome (you only need chr1-22 and XY). You will need to combine them into a single file.
2. There are essentially two types of raw data (BED-like format and bigwig format). I have put my scripts to this [folder](https://github.com/smshuai/DriverPower/tree/master/script/make_features). An example of making new features is also included [here](https://github.com/smshuai/DriverPower/tree/master/script/make_features/example). Just follow the `run_example.sh` and you will get an example feature table called `example_features.tsv` which can be used directly in DriverPower by replacing the hdf5 file.

I haven't fully tested this part and I'm planning to make a detailed tutorial on this part too. Let me know if you meet any problem.

Best,
Shimin

**Comment by yasunorikogure** [comment]
Hi Shimin,

Thank you so much for the resources.
I will try them and also be happy to share the result or any troubles.

Best,
Yasunori

**Comment by yasunorikogure** [comment]
Hi Shimin,

Finally, I completed replacing the original hdf5 file with my feature file.
I'd like to inform you one thing, that the script required enormous memory size when the number of elements was huge (especially in the bigwigToBed step). I had to split the tasks for parallel calculation.

Thanks a lot for your helpful info and codes!

Best,
Yasunori

**Comment by smshuai** [comment]
Hi Yasunori,

I'm glad to hear that you complete it! When there are a lot of elements (like a million), I only met memory issues for evolutionary score features in bigwig format. So in an HPC environment, I just ran them separately with a lot of memory.

I'm finalizing a script to auto-generate the database and I will put a note about potential high memory consumption.

Thanks for trying out!

Best,
Shimin
